### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by greenhandzdl** [lm175/nonebot-plugin-fakepic#1]
https://github.com/Cvandia/nonebot-plugin-fakemsg/issues/14

**Comment by lm175** [comment]
Linux系统一般没有默认的中文字体，如果是类似"口口口口口口口"的情况，可以尝试安装中文字体后再运行。
字体安装可参考此文档
[https://github.com/MeetWq/meme-generator/wiki/%E6%9C%AC%E5%9C%B0%E5%AE%89%E8%A3%85#%E5%AD%97%E4%BD%93%E5%AE%89%E8%A3%85](url)
如果您不是Linux环境或是其它情况的乱码，请提供更具体的信息

**Comment by greenhandzdl** [comment]
还是不行
```
-bash: neofethc: 未找到命令
root@www:~# neofetch
       _,met$$$$$gg.          root@www.greenhandzdl.moe 
    ,g$$$$$$$$$$$$$$$P.       ------------------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 12 (bookworm) x86_64 
 ,$$P'              `$$$.     Host: KVM RHEL 7.6.0 PC (i440FX + PIIX, 1996) 
',$$P       ,ggs.     `$$b:   Kernel: 6.1.0-27-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 4 mins 
 $$P      d$'     ,    $$P    Packages: 1716 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.2.15 
 $$;      Y$b._   _,d$P'      Resolution: 1024x768 
 Y$$.    `.`"Y$$$$P"'         Terminal: /dev/pts/0 
 `$$b      "-.__              CPU: Intel Xeon E5-2697 v2 (4) @ 2.699GHz 
  `Y$$                        GPU: 00:02.0 Cirrus Logic GD 5446 
   `Y$$.                      Memory: 753MiB / 1966MiB 
     `$$b.
       `Y$$b.                                         
          `"Y$b._                                     
              `"""
```

**Comment by lm175** [comment]
如果是用sudo安装的字体，请检查安装后的字体是否对普通用户具有可读权限，sudo安装的字体路径一般为`/usr/local/share/fonts/`
如果还是不行的话，可以把一个您确信可以使用的中文字体文件放在插件的`resource/`目录下（`bot_icon.png`所在目录），然后更改`draw.py`中的代码 
https://github.com/lm175/nonebot-plugin-fakepic/blob/aef2267fdf516fa17792509d8b3621678a3b58ec/nonebot_plugin_fakepic/draw.py#L10-L11
将这两行更改为
```
NICK_FONT = str(res_path / "msyhl.ttc") # 确保此处的字体名与resource中的字体名一致
CHAT_FONT = NICK_FONT
```
这样应该可以解决

**Comment by greenhandzdl** [comment]
> 如果是用sudo安装的字体，请检查安装后的字体是否对普通用户具有可读权限，sudo安装的字体路径一般为`/usr/local/share/fonts/`
> 如果还是不行的话，可以把一个您确信可以使用的中文字体文件放在插件的`resource/`目录下（`bot_icon.png`所在目录），然后更改`draw.py`中的代码 
> https://github.com/lm175/nonebot-plugin-fakepic/blob/aef2267fdf516fa17792509d8b3621678a3b58ec/nonebot_plugin_fakepic/draw.py#L10-L11
> 将这两行更改为
> ```
> NICK_FONT = str(res_path / "msyhl.ttc") # 确保此处的字体名与resource中的字体名一致
> CHAT_FONT = NICK_FONT
> ```
> 这样应该可以解决

问题来了，我root跑的nb

**Comment by lm175** [comment]
> 问题来了，我root跑的nb

试一下第二种解决方法，权限这些我也不太懂

**Comment by greenhandzdl** [comment]
> 如果是用sudo安装的字体，请检查安装后的字体是否对普通用户具有可读权限，sudo安装的字体路径一般为`/usr/local/share/fonts/` 如果还是不行的话，可以把一个您确信可以使用的中文字体文件放在插件的`resource/`目录下（`bot_icon.png`所在目录），然后更改`draw.py`中的代码
> 
> https://github.com/lm175/nonebot-plugin-fakepic/blob/aef2267fdf516fa17792509d8b3621678a3b58ec/nonebot_plugin_fakepic/draw.py#L10-L11
> 
> 
> 将这两行更改为
> ```
> NICK_FONT = str(res_path / "msyhl.ttc") # 确保此处的字体名与resource中的字体名一致
> CHAT_FONT = NICK_FONT
> ```
> 
> 这样应该可以解决

1.
```
root@www:~/nonebot/nbot/.venv/lib/python3.11/site-packages/nonebot_plugin_fakepic# ls /usr/local/share/fonts/
root@www:~/nonebot/nbot/.venv/lib/python3.11/site-packages/nonebot_plugin_fakepic# 

```
似乎没有文件
2.
```
root@www:~/nonebot/nbot/.venv/lib/python3.11/site-packages/nonebot_plugin_fakepic# pwd
/root/nonebot/nbot/.venv/lib/python3.11/site-packages/nonebot_plugin_fakepic
```
可以一股脑按照[字体](https://github.com/MeetWq/meme-generator/wiki/%E6%9C%AC%E5%9C%B0%E5%AE%89%E8%A3%85#%E5%AD%97%E4%BD%93%E5%AE%89%E8%A3%85)复制过来吗

**Comment by lm175** [comment]
> > 如果是用sudo安装的字体，请检查安装后的字体是否对普通用户具有可读权限，sudo安装的字体路径一般为`/usr/local/share/fonts/` 如果还是不行的话，可以把一个您确信可以使用的中文字体文件放在插件的`resource/`目录下（`bot_icon.png`所在目录），然后更改`draw.py`中的代码
> > https://github.com/lm175/nonebot-plugin-fakepic/blob/aef2267fdf516fa17792509d8b3621678a3b58ec/nonebot_plugin_fakepic/draw.py#L10-L11
> > 
> > 将这两行更改为
> > ```
> > NICK_FONT = str(res_path / "msyhl.ttc") # 确保此处的字体名与resource中的字体名一致
> > CHAT_FONT = NICK_FONT
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样应该可以解决
> 
> 
> ```
> root@www:~/nonebot/nbot/.venv/lib/python3.11/site-packages/nonebot_plugin_fakepic# ls /usr/local/share/fonts/
> root@www:~/nonebot/nbot/.venv/lib/python3.11/site-packages/nonebot_plugin_fakepic# 
> ```
> 
> 似乎没有文件 2.
> 
> ```
> root@www:~/nonebot/nbot/.venv/lib/python3.11/site-packages/nonebot_plugin_fakepic# pwd
> /root/nonebot/nbot/.venv/lib/python3.11/site-packages/nonebot_plugin_fakepic
> ```
> 
> 可以一股脑按照[字体](https://github.com/MeetWq/meme-generator/wiki/%E6%9C%AC%E5%9C%B0%E5%AE%89%E8%A3%85#%E5%AD%97%E4%BD%93%E5%AE%89%E8%A3%85)复制过来吗

使用一个字体即可，例如可以将自己电脑中的微软雅黑复制到
`/root/nonebot/nbot/.venv/lib/python3.11/site-packages/nonebot_plugin_fakepic/resource/`
然后在`draw.py`中指定复制过去的字体文件

**Comment by greenhandzdl** [comment]
但是，我电脑里面没有微软这些字体。。

**Comment by lm175** [comment]
> 但是，我电脑里面没有微软这些字体。。

只要是中文字体就可以

**Comment by greenhandzdl** [comment]
<img width="506" alt="截屏2024-11-16 15 34 03" src="https://github.com/user-attachments/assets/764b4d37-1033-4932-a29b-da278e003983">

NICK_FONT = str(res_path / "微软雅黑.ttf") 
CHAT_FONT = NICK_FONT
